apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: allthatjazzleo/golang_url_shortener
    context: src/app
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}

