apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
    tier: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: url-shortener
        tier: api
    spec:
      containers:
      - name: url-shortener
        image: allthatjazzleo/golang_url_shortener
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: REDIS_ENDPOINT
          value: redis-master
